default: &default
  :browser_type: 'firefox'
  :url: 'http://google.com'
user1:
  <<: *default  
  :name: 'User 1'
  :login: 'user1'
  :password: 'Provenir1'
user2:
  <<: *default
  :name: 'User 2'
  :login: 'user2'
  :password: 'Provenir1'

