default: &default
  :url: 'http://google.com'
user1:
  <<: *default  
  :name: 'User 1'
  :login: 'user1'
  :password: 'abc'
user2:
  <<: *default
  :name: 'User 2'
  :login: 'user2'
  :password: 'xyz'