default: &default
  # :url: 'https://qa.provapps.com/ProvAppCLWeb/'
  # :url: 'http://provappsvpcqa01.provapps.com:6080/ProvAppCLWeb/'  
  #:url: 'http://10.40.100.193:7001//ProvAppCLWeb/'
  #:url: 'http://provappsvpcwl01.provapps.com:7001/ProvAppCLWeb/'
  #:url: 'http://was01.provapps.com:9080/ProvAppCLWeb/'
  :url: 'http://10.40.100.167:7001/ProvAppCLWeb/'
fmartin:
  <<: *default  
  :name: 'Frank Martin'
  :login: 'fmartin'
  :password: 'Provenir1'
clientspcl:
  <<: *default
  :name: 'Client Specialist User'
  :login: 'clientspcl'
  :password: 'Provenir1'
provadmin:
  <<: *default
  :name: 'Provenir Admin User'
  :login: 'provadmin'
  :password: 'Provenir1'